/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hetfruithuisje;

import java.awt.CardLayout;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanelCustomers = new javax.swing.JPanel();
        jCustomersTitle = new javax.swing.JLabel();
        jPanelProducts = new javax.swing.JPanel();
        jProductsTitle = new javax.swing.JLabel();
        jPanelOrders = new javax.swing.JPanel();
        jOrdersTitle = new javax.swing.JLabel();
        jBtnCustomers = new javax.swing.JButton();
        jBtnProducts = new javax.swing.JButton();
        jBtnOrders = new javax.swing.JButton();
        jBtnLogout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 480));
        getContentPane().setLayout(null);

        mainPanel.setLayout(new java.awt.CardLayout());

        jCustomersTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jCustomersTitle.setForeground(new java.awt.Color(0, 102, 255));
        jCustomersTitle.setText("Klanten Overzicht");

        javax.swing.GroupLayout jPanelCustomersLayout = new javax.swing.GroupLayout(jPanelCustomers);
        jPanelCustomers.setLayout(jPanelCustomersLayout);
        jPanelCustomersLayout.setHorizontalGroup(
            jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomersLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jCustomersTitle)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanelCustomersLayout.setVerticalGroup(
            jPanelCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomersLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jCustomersTitle)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        mainPanel.add(jPanelCustomers, "jPanelCustomers");

        jProductsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jProductsTitle.setForeground(new java.awt.Color(0, 102, 255));
        jProductsTitle.setText("Producten Overzicht");

        javax.swing.GroupLayout jPanelProductsLayout = new javax.swing.GroupLayout(jPanelProducts);
        jPanelProducts.setLayout(jPanelProductsLayout);
        jPanelProductsLayout.setHorizontalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jProductsTitle)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanelProductsLayout.setVerticalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jProductsTitle)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        mainPanel.add(jPanelProducts, "jPanelProducts");

        jOrdersTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jOrdersTitle.setForeground(new java.awt.Color(0, 102, 255));
        jOrdersTitle.setText("Bestellingen Overzicht");

        javax.swing.GroupLayout jPanelOrdersLayout = new javax.swing.GroupLayout(jPanelOrders);
        jPanelOrders.setLayout(jPanelOrdersLayout);
        jPanelOrdersLayout.setHorizontalGroup(
            jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdersLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jOrdersTitle)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanelOrdersLayout.setVerticalGroup(
            jPanelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdersLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jOrdersTitle)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        mainPanel.add(jPanelOrders, "jPanelOrders");

        getContentPane().add(mainPanel);
        mainPanel.setBounds(200, 0, 500, 470);

        jBtnCustomers.setText("Klanten Overzicht");
        jBtnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustomersActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCustomers);
        jBtnCustomers.setBounds(6, 30, 190, 70);

        jBtnProducts.setText("Producten Overzicht");
        jBtnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProductsActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnProducts);
        jBtnProducts.setBounds(6, 136, 190, 69);

        jBtnOrders.setText("Bestellingen Overzicht");
        jBtnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnOrders);
        jBtnOrders.setBounds(6, 238, 190, 70);

        jBtnLogout.setText("Uitloggen");
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnLogout);
        jBtnLogout.setBounds(10, 410, 180, 42);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hetfruithuisje/images/bg.png"))); // NOI18N
        background.setText("jLabel2");
        getContentPane().add(background);
        background.setBounds(1, 1, 700, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustomersActionPerformed
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "jPanelCustomers");
        
    }//GEN-LAST:event_jBtnCustomersActionPerformed

    private void jBtnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProductsActionPerformed
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "jPanelProducts");
        
    }//GEN-LAST:event_jBtnProductsActionPerformed

    private void jBtnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOrdersActionPerformed
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "jPanelOrders");
        
    }//GEN-LAST:event_jBtnOrdersActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        Login j = new Login();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jBtnCustomers;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnOrders;
    private javax.swing.JButton jBtnProducts;
    private javax.swing.JLabel jCustomersTitle;
    private javax.swing.JLabel jOrdersTitle;
    private javax.swing.JPanel jPanelCustomers;
    private javax.swing.JPanel jPanelOrders;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JLabel jProductsTitle;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
